// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACdINe7m6N-5BhLg22NRQY2wMA9XJ3I5M',
    appId: '1:317902245714:web:320c683e3ff7fa9e03348b',
    messagingSenderId: '317902245714',
    projectId: 'product-27ea9',
    authDomain: 'product-27ea9.firebaseapp.com',
    storageBucket: 'product-27ea9.firebasestorage.app',
    measurementId: 'G-V6B6624EFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVik4Mg7WOZ4U71DpDWzBBNM1mndYUWRo',
    appId: '1:317902245714:android:911f7e74494f26ce03348b',
    messagingSenderId: '317902245714',
    projectId: 'product-27ea9',
    storageBucket: 'product-27ea9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeBN_20BEW9_JBXf5GRp41p3UWkwDyqaU',
    appId: '1:317902245714:ios:1e5b8d10b22b70be03348b',
    messagingSenderId: '317902245714',
    projectId: 'product-27ea9',
    storageBucket: 'product-27ea9.firebasestorage.app',
    iosBundleId: 'com.example.demo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeBN_20BEW9_JBXf5GRp41p3UWkwDyqaU',
    appId: '1:317902245714:ios:1e5b8d10b22b70be03348b',
    messagingSenderId: '317902245714',
    projectId: 'product-27ea9',
    storageBucket: 'product-27ea9.firebasestorage.app',
    iosBundleId: 'com.example.demo1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACdINe7m6N-5BhLg22NRQY2wMA9XJ3I5M',
    appId: '1:317902245714:web:52e84079dd2ddc8903348b',
    messagingSenderId: '317902245714',
    projectId: 'product-27ea9',
    authDomain: 'product-27ea9.firebaseapp.com',
    storageBucket: 'product-27ea9.firebasestorage.app',
    measurementId: 'G-FJNWCMF42D',
  );

}